Repository knative/observability, pull requests merged in 2019-05, with the labels that each got.

#26 Add namespace metric sink
  .envrc
  README.md
  cmd/metric-controller/main.go
  config/200-metric-controller-roles.yaml
  config/401-validator-webhook-config.yaml
  go.sum
  pkg/apis/sink/v1alpha1/register.go
  pkg/apis/sink/v1alpha1/types.go
  pkg/apis/sink/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/sink/v1alpha1/fake/fake_metricsink.go
  pkg/client/clientset/versioned/typed/sink/v1alpha1/fake/fake_sink_client.go
  pkg/client/clientset/versioned/typed/sink/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/sink/v1alpha1/metricsink.go
  pkg/client/clientset/versioned/typed/sink/v1alpha1/sink_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/sink/v1alpha1/interface.go
  pkg/client/informers/externalversions/sink/v1alpha1/metricsink.go
  pkg/client/listers/sink/v1alpha1/expansion_generated.go
  pkg/client/listers/sink/v1alpha1/metricsink.go
  pkg/metric/cluster_config.go
  pkg/metric/cluster_config_test.go
  pkg/metric/cluster_controller.go
  pkg/metric/cluster_controller_test.go
  pkg/metric/common.go
  pkg/metric/config.go
  pkg/metric/controller.go
  pkg/metric/controller_test.go
  pkg/webhook/server.go
  pkg/webhook/server_test.go
  test/crd/invalid/metric-sink-invalid-datadog-config.yaml
  test/crd/invalid/metric-sink-missing-inputs.yaml
  test/crd/valid/metric-sink.yaml
  test/e2e/clustermetricsink_test.go
  test/e2e/metricsink_test.go
  test/e2e/setup_test.go
  vendor/modules.txt
Labels: approved, size/XXL

#27 Simplify testing initialize function
  test/e2e/clusterlogsink_test.go
  test/e2e/clustermetricsink_test.go
  test/e2e/logsink_test.go
  test/e2e/metricsink_test.go
  test/e2e/setup_test.go
Labels: approved, cla: yes, lgtm, size/S

#28 Update test-infra: get rid of Unbound variable running update-deps wa…
  go.mod
  go.sum
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L
